/**
 * Golden Recipes Registry for Körset AI.
 * 25 curated popular supermarket recipes in Kazakhstan with strictly scoped
 * culinary roles, target categories, search terms, and exclusions.
 */

export const GOLDEN_RECIPES = [
  {
    id: 'burger',
    title: { ru: 'Домашние бургеры', kz: 'Үй бургері' },
    emoji: '🍔',
    aliases: ['бургер', 'бургеры', 'гамбургер', 'чизбургер', 'бургерлер', 'burger'],
    roles: [
      {
        id: 'buns',
        title: { ru: 'Булочки для бургера', kz: 'Бургер тоқаштары' },
        category: 'bread',
        queryTerms: ['булочки для бургера', 'булочка для гамбургера', 'булочки bagerstat', 'булочки'],
        excludeCategories: ['sweets'],
        required: true,
      },
      {
        id: 'meat',
        title: { ru: 'Фарш или котлеты', kz: 'Фарш немесе котлет' },
        category: 'meat',
        queryTerms: ['фарш говядина', 'фарш говяжий', 'фарш куриный', 'котлеты'],
        excludeCategories: ['pet_supplies'],
        required: true,
      },
      {
        id: 'cheese',
        title: { ru: 'Сыр Чеддер', kz: 'Чеддер ірімшігі' },
        category: 'dairy_eggs',
        queryTerms: ['сыр чеддер ломтики', 'сыр burger чеддер', 'сыр плавленый ломтики', 'чеддер'],
        required: true,
      },
      {
        id: 'veg',
        title: { ru: 'Свежие овощи и зелень', kz: 'Жаңа піскен көкөністер' },
        category: 'fruits_veg',
        queryTerms: ['помидоры черри', 'помидоры', 'огурцы', 'салат айсберг'],
        excludeCategories: ['sauces_spices', 'grocery'],
        required: true,
      },
      {
        id: 'sauce',
        title: { ru: 'Соус для бургера', kz: 'Бургер тұздығы' },
        category: 'sauces_spices',
        queryTerms: ['соус для бургеров', 'соус бургер', 'кетчуп heinz', 'кетчуп'],
        required: false,
      },
    ],
  },
  {
    id: 'plov',
    title: { ru: 'Классический плов', kz: 'Дәстүрлі палау' },
    emoji: '🍲',
    aliases: ['плов', 'палау', 'пловка', 'plov'],
    roles: [
      {
        id: 'rice',
        title: { ru: 'Рис для плова', kz: 'Палау күріші' },
        category: 'grocery',
        queryTerms: ['рис лазер', 'рис девзира', 'рис для плова', 'рис басмати', 'рис круглый'],
        required: true,
      },
      {
        id: 'meat',
        title: { ru: 'Мясо (говядина или баранина)', kz: 'Ет (сиыр немесе қой)' },
        category: 'meat',
        queryTerms: ['говядина мякоть', 'говядина лопатка', 'говядина', 'баранина'],
        required: true,
      },
      {
        id: 'carrot',
        title: { ru: 'Морковь и лук', kz: 'Сәбіз бен пияз' },
        category: 'fruits_veg',
        queryTerms: ['морковь', 'лук репчатый'],
        required: true,
      },
      {
        id: 'oil',
        title: { ru: 'Растительное масло', kz: 'Өсімдік майы' },
        category: 'grocery',
        queryTerms: ['масло подсолнечное', 'масло хлопковое', 'масло шедевр'],
        required: true,
      },
      {
        id: 'spices',
        title: { ru: 'Зира и приправы', kz: 'Зире және дәмдеуіштер' },
        category: 'sauces_spices',
        queryTerms: ['приправа для плова', 'зира', 'чеснок'],
        required: false,
      },
    ],
  },
  {
    id: 'manty',
    title: { ru: 'Манты с мясом', kz: 'Ет мәнтісі' },
    emoji: '🥟',
    aliases: ['манты', 'мәнті', 'мантылар', 'manty'],
    roles: [
      {
        id: 'meat',
        title: { ru: 'Мясо или фарш', kz: 'Ет немесе тартылған ет' },
        category: 'meat',
        queryTerms: ['говядина мякоть', 'фарш говяжий', 'фарш домашний'],
        required: true,
      },
      {
        id: 'flour',
        title: { ru: 'Мука высший сорт', kz: 'Жоғары сұрыпты ұн' },
        category: 'grocery',
        queryTerms: ['мука цесна', 'мука пшеничная', 'мука 2кг'],
        required: true,
      },
      {
        id: 'onion',
        title: { ru: 'Лук репчатый', kz: 'Бас пияз' },
        category: 'fruits_veg',
        queryTerms: ['лук репчатый', 'лук'],
        required: true,
      },
      {
        id: 'spices_salt',
        title: { ru: 'Черный перец и соль', kz: 'Қара бұрыш пен тұз' },
        category: 'sauces_spices',
        queryTerms: ['перец черный молотый', 'приправа для манты'],
        required: false,
      },
    ],
  },
  {
    id: 'beshbarmak',
    title: { ru: 'Бешбармак', kz: 'Бесбармақ' },
    emoji: '🍖',
    aliases: ['бешбармак', 'бесбармақ', 'ет', 'ет асу', 'beshbarmak'],
    roles: [
      {
        id: 'meat',
        title: { ru: 'Мясо (конина или говядина)', kz: 'Ет (жылқы немесе сиыр)' },
        category: 'meat',
        queryTerms: ['говядина мякоть', 'конина', 'говядина на кости'],
        required: true,
      },
      {
        id: 'noodles',
        title: { ru: 'Сочни / жайма для бешбармака', kz: 'Жайма / бесбармақ қамыры' },
        category: 'grocery',
        queryTerms: ['сочни для бешбармака', 'жайма', 'лапша для бешбармака', 'кеспе'],
        required: true,
      },
      {
        id: 'onion',
        title: { ru: 'Лук для туздыка', kz: 'Тұздыққа арналған пияз' },
        category: 'fruits_veg',
        queryTerms: ['лук репчатый', 'лук'],
        required: true,
      },
      {
        id: 'pepper',
        title: { ru: 'Черный перец', kz: 'Қара бұрыш' },
        category: 'sauces_spices',
        queryTerms: ['перец черный молотый', 'перец черный горошек'],
        required: false,
      },
    ],
  },
  {
    id: 'borscht',
    title: { ru: 'Борщ со сметаной', kz: 'Борщ қаймақпен' },
    emoji: '🥣',
    aliases: ['борщ', 'борщ со сметаной', 'борщқа', 'borscht'],
    roles: [
      {
        id: 'meat',
        title: { ru: 'Мясо на бульон', kz: 'Сорпаға арналған ет' },
        category: 'meat',
        queryTerms: ['говядина на кости', 'говядина мякоть', 'суповой набор говядина'],
        required: true,
      },
      {
        id: 'beetroot_veg',
        title: { ru: 'Свекла, капуста и морковь', kz: 'Қызылша, қырыққабат және сәбіз' },
        category: 'fruits_veg',
        queryTerms: ['свекла', 'капуста белокочанная', 'морковь', 'картофель'],
        required: true,
      },
      {
        id: 'paste',
        title: { ru: 'Томатная паста', kz: 'Томат пастасы' },
        category: 'grocery',
        queryTerms: ['томатная паста', 'помидорка паста', 'томатная паста 70гр'],
        required: true,
      },
      {
        id: 'sour_cream',
        title: { ru: 'Сметана', kz: 'Қаймақ' },
        category: 'dairy_eggs',
        queryTerms: ['сметана 15%', 'сметана 20%', 'сметана президент', 'сметана'],
        required: true,
      },
    ],
  },
  {
    id: 'pasta_carbonara',
    title: { ru: 'Паста Карбонара', kz: 'Карбонара пастасы' },
    emoji: '🍝',
    aliases: ['карбонара', 'паста карбонара', 'макароны карбонара', 'carbonara'],
    roles: [
      {
        id: 'pasta',
        title: { ru: 'Спагетти из твердых сортов', kz: 'Қатты бидайдан жасалған спагетти' },
        category: 'grocery',
        queryTerms: ['спагетти barilla', 'спагетти federici', 'спагетти', 'макароны barilla'],
        required: true,
      },
      {
        id: 'bacon',
        title: { ru: 'Бекон или ветчина', kz: 'Бекон немесе ет өнімі' },
        category: 'deli',
        queryTerms: ['бекон сырокопченый', 'бекон нарезка', 'грудинка сырокопченая'],
        required: true,
      },
      {
        id: 'cream',
        title: { ru: 'Сливки 20% или 10%', kz: 'Кілегей 20% немесе 10%' },
        category: 'dairy_eggs',
        queryTerms: ['сливки 20%', 'сливки 10%', 'сливки для соуса'],
        required: true,
      },
      {
        id: 'cheese',
        title: { ru: 'Твердый сыр (Пармезан)', kz: 'Қатты ірімшік (Пармезан)' },
        category: 'dairy_eggs',
        queryTerms: ['сыр пармезан', 'сыр твердый', 'сыр grana padano'],
        required: true,
      },
    ],
  },
  {
    id: 'breakfast_oatmeal',
    title: { ru: 'Завтрак с овсянкой и фруктами', kz: 'Сұлы ботқасы мен жемістер' },
    emoji: '🍳',
    aliases: ['завтрак', 'овсянка', 'каша', 'таңғы ас', 'breakfast'],
    roles: [
      {
        id: 'oats',
        title: { ru: 'Овсяные хлопья', kz: 'Сұлы үлпектері' },
        category: 'grocery',
        queryTerms: ['овсяные хлопья геркулес', 'хлопья овсяные ясно солнышко', 'овсяные хлопья'],
        required: true,
      },
      {
        id: 'milk',
        title: { ru: 'Молоко', kz: 'Сүт' },
        category: 'dairy_eggs',
        queryTerms: ['молоко 2.5%', 'молоко 3.2%', 'молоко петропавловское', 'молоко'],
        required: true,
      },
      {
        id: 'eggs',
        title: { ru: 'Куриные яйца', kz: 'Тауық жұмыртқасы' },
        category: 'dairy_eggs',
        queryTerms: ['яйцо куриное с1', 'яйца с0', 'яйцо 10шт'],
        required: true,
      },
      {
        id: 'fruit',
        title: { ru: 'Бананы или ягоды', kz: 'Банан немесе жидектер' },
        category: 'fruits_veg',
        queryTerms: ['бананы', 'яблоки', 'ягоды замороженные'],
        required: false,
      },
    ],
  },
  {
    id: 'syrniki',
    title: { ru: 'Сырники домашние', kz: 'Үй сүзбешелері' },
    emoji: '🥞',
    aliases: ['сырники', 'сырник', 'сүзбеше', 'творожники', 'syrniki'],
    roles: [
      {
        id: 'tvorog',
        title: { ru: 'Творог 5% или 9%', kz: 'Сүзбе 5% немесе 9%' },
        category: 'dairy_eggs',
        queryTerms: ['творог 5%', 'творог 9%', 'творог домашний', 'творог простоквашино'],
        required: true,
      },
      {
        id: 'eggs',
        title: { ru: 'Яйцо куриное', kz: 'Тауық жұмыртқасы' },
        category: 'dairy_eggs',
        queryTerms: ['яйцо куриное с1', 'яйцо 10шт'],
        required: true,
      },
      {
        id: 'flour',
        title: { ru: 'Мука пшеничная', kz: 'Бидай ұны' },
        category: 'grocery',
        queryTerms: ['мука пшеничная 1кг', 'мука цесна'],
        required: true,
      },
      {
        id: 'sugar_vanilla',
        title: { ru: 'Сахар и ванилин', kz: 'Қант және ванилин' },
        category: 'grocery',
        queryTerms: ['сахар песок', 'ванилин'],
        required: false,
      },
      {
        id: 'sour_cream',
        title: { ru: 'Сметана к подаче', kz: 'Қаймақ' },
        category: 'dairy_eggs',
        queryTerms: ['сметана 15%', 'сметана 20%'],
        required: false,
      },
    ],
  },
  {
    id: 'pizza',
    title: { ru: 'Домашняя пицца', kz: 'Үй пиццасы' },
    emoji: '🍕',
    aliases: ['пицца', 'пиццаға', 'pizza'],
    roles: [
      {
        id: 'dough_or_base',
        title: { ru: 'Тесто или основа для пиццы', kz: 'Пицца қамыры' },
        category: 'frozen',
        queryTerms: ['тесто слоеное', 'основа для пиццы', 'тесто дрожжевое'],
        required: true,
      },
      {
        id: 'cheese',
        title: { ru: 'Сыр Моцарелла', kz: 'Моцарелла ірімшігі' },
        category: 'dairy_eggs',
        queryTerms: ['сыр моцарелла', 'сыр для пиццы моцарелла', 'моцарелла пицца'],
        required: true,
      },
      {
        id: 'meat_topping',
        title: { ru: 'Колбаса пепперони или ветчина', kz: 'Пепперони шұжығы немесе ет' },
        category: 'deli',
        queryTerms: ['колбаса пепперони', 'колбаса салями', 'ветчина из индейки'],
        required: true,
      },
      {
        id: 'sauce',
        title: { ru: 'Томатный соус для пиццы', kz: 'Пиццаға арналған қызанақ тұздығы' },
        category: 'sauces_spices',
        queryTerms: ['соус томатный barilla', 'томатная паста', 'кетчуп'],
        required: true,
      },
    ],
  },
  {
    id: 'shashlik',
    title: { ru: 'Шашлык с маринадом', kz: 'Кәуап және маринад' },
    emoji: '🍢',
    aliases: ['шашлык', 'кәуап', 'мясо для шашлыка', 'шашлыкка', 'shashlik'],
    roles: [
      {
        id: 'meat',
        title: { ru: 'Мясо (говядина, баранина или курица)', kz: 'Ет (сиыр, қой немесе тауық)' },
        category: 'meat',
        queryTerms: ['говядина вырезка', 'куриное филе', 'крылья куриные', 'баранина корейка'],
        required: true,
      },
      {
        id: 'onion',
        title: { ru: 'Лук репчатый для маринада', kz: 'Маринадқа арналған пияз' },
        category: 'fruits_veg',
        queryTerms: ['лук репчатый', 'лук'],
        required: true,
      },
      {
        id: 'spices',
        title: { ru: 'Приправа для шашлыка', kz: 'Кәуап дәмдеуіші' },
        category: 'sauces_spices',
        queryTerms: ['приправа для шашлыка', 'кориандр молотый', 'паприка копченая'],
        required: true,
      },
      {
        id: 'sauce',
        title: { ru: 'Соус шашлычный', kz: 'Кәуап тұздығы' },
        category: 'sauces_spices',
        queryTerms: ['кетчуп шашлычный', 'соус ткемали', 'кетчуп махеевъ'],
        required: false,
      },
    ],
  },
  {
    id: 'chicken_soup',
    title: { ru: 'Куриный суп с лапшой', kz: 'Тауық еті қосылған кеспе көже' },
    emoji: '🍲',
    aliases: ['куриный суп', 'суп с курицей', 'кеспе көже', 'лапша куриная'],
    roles: [
      {
        id: 'chicken',
        title: { ru: 'Курица на бульон', kz: 'Сорпаға арналған тауық еті' },
        category: 'meat',
        queryTerms: ['суповой набор куриный', 'бедро куриное', 'курица тушка', 'голень куриная'],
        required: true,
      },
      {
        id: 'noodles',
        title: { ru: 'Суповая лапша / кеспе', kz: 'Көжеге арналған кеспе' },
        category: 'grocery',
        queryTerms: ['лапша яичная', 'кеспе домашняя', 'вермишель паутинка'],
        required: true,
      },
      {
        id: 'veg',
        title: { ru: 'Картофель, морковь и лук', kz: 'Картоп, сәбіз және пияз' },
        category: 'fruits_veg',
        queryTerms: ['картофель', 'морковь', 'лук репчатый', 'укроп'],
        required: true,
      },
    ],
  },
  {
    id: 'olivier',
    title: { ru: 'Салат Оливье', kz: 'Оливье салаты' },
    emoji: '🥗',
    aliases: ['оливье', 'салат оливье', 'olivier'],
    roles: [
      {
        id: 'sausage_or_meat',
        title: { ru: 'Докторская колбаса или мясо', kz: 'Дәрігерлік шұжық немесе ет' },
        category: 'deli',
        queryTerms: ['колбаса докторская', 'колбаса молочная', 'филе куриное'],
        required: true,
      },
      {
        id: 'peas',
        title: { ru: 'Зеленый горошек', kz: 'Жасыл бұршақ' },
        category: 'grocery',
        queryTerms: ['горошек зеленый консервированный', 'горошек bonduelle', 'горошек'],
        required: true,
      },
      {
        id: 'mayo',
        title: { ru: 'Майонез Провансаль', kz: 'Провансаль майонезі' },
        category: 'sauces_spices',
        queryTerms: ['майонез провансаль 67%', 'майонез махеевъ', 'майонез слобода'],
        required: true,
      },
      {
        id: 'veg_eggs',
        title: { ru: 'Картофель, огурцы маринованные, яйца', kz: 'Картоп, тұздалған қияр, жұмыртқа' },
        category: 'fruits_veg',
        queryTerms: ['картофель', 'огурцы соленые', 'огурцы маринованные', 'морковь'],
        required: true,
      },
    ],
  },
  {
    id: 'caesar',
    title: { ru: 'Салат Цезарь с курицей', kz: 'Тауық еті бар Цезарь салаты' },
    emoji: '🥗',
    aliases: ['цезарь', 'салат цезарь', 'caesar'],
    roles: [
      {
        id: 'chicken',
        title: { ru: 'Куриное филе', kz: 'Тауық сүбесі' },
        category: 'meat',
        queryTerms: ['филе куриное охлажденное', 'филе курицы', 'грудка куриная'],
        required: true,
      },
      {
        id: 'lettuce',
        title: { ru: 'Салат Айсберг или Романо', kz: 'Айсберг салаты' },
        category: 'fruits_veg',
        queryTerms: ['салат айсберг', 'салат листовой', 'помидоры черри'],
        required: true,
      },
      {
        id: 'cheese',
        title: { ru: 'Сыр Пармезан', kz: 'Пармезан ірімшігі' },
        category: 'dairy_eggs',
        queryTerms: ['сыр пармезан тертый', 'сыр пармезан', 'сыр твердый'],
        required: true,
      },
      {
        id: 'sauce',
        title: { ru: 'Соус Цезарь', kz: 'Цезарь тұздығы' },
        category: 'sauces_spices',
        queryTerms: ['соус цезарь heinz', 'соус цезарь kuhne', 'соус цезарь'],
        required: true,
      },
      {
        id: 'croutons',
        title: { ru: 'Сухарики для салата', kz: 'Салатқа арналған қытырлақ нан' },
        category: 'snacks',
        queryTerms: ['сухарики багет', 'крутоны', 'сухарики хрустеам'],
        required: false,
      },
    ],
  },
  {
    id: 'steak',
    title: { ru: 'Стейк с овощами', kz: 'Көкөністер қосылған стейк' },
    emoji: '🥩',
    aliases: ['стейк', 'говяжий стейк', 'рибай', 'мясо для стейка', 'steak'],
    roles: [
      {
        id: 'meat',
        title: { ru: 'Стейк из говядины', kz: 'Сиыр етінен жасалған стейк' },
        category: 'meat',
        queryTerms: ['стейк рибай', 'стейк стриплойн', 'говядина вырезка', 'стейк'],
        required: true,
      },
      {
        id: 'veg',
        title: { ru: 'Овощи на гарнир', kz: 'Гарнирге арналған көкөністер' },
        category: 'fruits_veg',
        queryTerms: ['перец болгарский', 'помидоры черри', 'кабачки', 'шампиньоны'],
        required: true,
      },
      {
        id: 'butter_oil',
        title: { ru: 'Сливочное или оливковое масло', kz: 'Сары май немесе зәйтүн майы' },
        category: 'dairy_eggs',
        queryTerms: ['масло сливочное 82.5%', 'масло оливковое extra virgin'],
        required: true,
      },
      {
        id: 'spices',
        title: { ru: 'Розмарин, чеснок и перец', kz: 'Розмарин, сарымсақ, бұрыш' },
        category: 'sauces_spices',
        queryTerms: ['розмарин', 'перец смесь перцев', 'чеснок свежий'],
        required: false,
      },
    ],
  },
  {
    id: 'pancakes',
    title: { ru: 'Домашние блины', kz: 'Үй құймақтары' },
    emoji: '🥞',
    aliases: ['блины', 'блинчики', 'құймақ', 'pancakes', 'blini'],
    roles: [
      {
        id: 'milk',
        title: { ru: 'Молоко', kz: 'Сүт' },
        category: 'dairy_eggs',
        queryTerms: ['молоко 2.5%', 'молоко 3.2%'],
        required: true,
      },
      {
        id: 'flour',
        title: { ru: 'Мука', kz: 'Ұн' },
        category: 'grocery',
        queryTerms: ['мука пшеничная цесна', 'мука 1кг'],
        required: true,
      },
      {
        id: 'eggs',
        title: { ru: 'Яйца куриные', kz: 'Тауық жұмыртқасы' },
        category: 'dairy_eggs',
        queryTerms: ['яйцо с1', 'яйца 10шт'],
        required: true,
      },
      {
        id: 'topping',
        title: { ru: 'Сгущенка или варенье', kz: 'Қоюлатылған сүт немесе тосап' },
        category: 'dairy_eggs',
        queryTerms: ['молоко сгущенное', 'сгущенка алексеевское', 'джем клубничный'],
        required: false,
      },
    ],
  },
  {
    id: 'buckwheat_meat',
    title: { ru: 'Гречка с мясом и подливой', kz: 'Ет қосылған қарақұмық' },
    emoji: '🍲',
    aliases: ['гречка с мясом', 'гречка', 'қарақұмық', 'buckwheat'],
    roles: [
      {
        id: 'buckwheat',
        title: { ru: 'Гречневая крупа', kz: 'Қарақұмық жармасы' },
        category: 'grocery',
        queryTerms: ['гречка увелка', 'крупа гречневая ядрица', 'гречка'],
        required: true,
      },
      {
        id: 'meat',
        title: { ru: 'Говядина или тушенка', kz: 'Сиыр еті немесе бұқтырылған ет' },
        category: 'meat',
        queryTerms: ['говядина мякоть', 'тушенка говяжья высший сорт', 'фарш говяжий'],
        required: true,
      },
      {
        id: 'onion_carrot',
        title: { ru: 'Лук и морковь', kz: 'Пияз бен сәбіз' },
        category: 'fruits_veg',
        queryTerms: ['лук репчатый', 'морковь'],
        required: true,
      },
    ],
  },
  {
    id: 'laghman',
    title: { ru: 'Лагман по-домашнему', kz: 'Үй лағманы' },
    emoji: '🍜',
    aliases: ['лагман', 'лағман', 'lagman', 'laghman'],
    roles: [
      {
        id: 'meat',
        title: { ru: 'Мякоть говядины', kz: 'Сиыр етінің жұмсағы' },
        category: 'meat',
        queryTerms: ['говядина мякоть', 'говядина лопатка'],
        required: true,
      },
      {
        id: 'noodles',
        title: { ru: 'Лапша для лагмана', kz: 'Лағман кеспесі' },
        category: 'grocery',
        queryTerms: ['лапша для лагмана', 'лагманная лапша', 'спагетти толстые'],
        required: true,
      },
      {
        id: 'veg',
        title: { ru: 'Болгарский перец, сельдерей, помидоры', kz: 'Бұрыш, қызанақ, сельдерей' },
        category: 'fruits_veg',
        queryTerms: ['перец болгарский светофор', 'помидоры', 'редька', 'чеснок'],
        required: true,
      },
      {
        id: 'paste_oil',
        title: { ru: 'Томатная паста и масло', kz: 'Томат пастасы және май' },
        category: 'grocery',
        queryTerms: ['томатная паста', 'масло растительное'],
        required: true,
      },
    ],
  },
  {
    id: 'samsa',
    title: { ru: 'Самса с мясом', kz: 'Ет самсасы' },
    emoji: '🥟',
    aliases: ['самса', 'самсалар', 'samsa'],
    roles: [
      {
        id: 'meat',
        title: { ru: 'Мясо или фарш', kz: 'Ет немесе тартылған ет' },
        category: 'meat',
        queryTerms: ['фарш говяжий жирный', 'говядина мякоть', 'фарш домашний'],
        required: true,
      },
      {
        id: 'dough',
        title: { ru: 'Слоеное тесто', kz: 'Қатпарлы қамыр' },
        category: 'frozen',
        queryTerms: ['тесто слоеное бездрожжевое', 'тесто слоеное'],
        required: true,
      },
      {
        id: 'onion_spices',
        title: { ru: 'Лук и зира', kz: 'Пияз және зире' },
        category: 'fruits_veg',
        queryTerms: ['лук репчатый', 'зира приправа'],
        required: true,
      },
    ],
  },
  {
    id: 'solyanka',
    title: { ru: 'Мясная солянка', kz: 'Ет солянкасы' },
    emoji: '🍲',
    aliases: ['солянка', 'солянка мясная', 'солянкаға', 'solyanka'],
    roles: [
      {
        id: 'meats',
        title: { ru: 'Мясное ассорти и копчености', kz: 'Ет ассортиі мен ысталған өнімдер' },
        category: 'deli',
        queryTerms: ['колбаса варено-копченая', 'грудинка', 'сосиски молочные', 'охотничьи колбаски'],
        required: true,
      },
      {
        id: 'pickles',
        title: { ru: 'Огурцы соленые и оливки', kz: 'Тұздалған қияр және зәйтүн' },
        category: 'grocery',
        queryTerms: ['огурцы соленые бочковые', 'маслины без косточки', 'оливки без косточки'],
        required: true,
      },
      {
        id: 'paste',
        title: { ru: 'Томатная паста и лимон', kz: 'Томат пастасы және лимон' },
        category: 'grocery',
        queryTerms: ['томатная паста помидорка', 'лимон'],
        required: true,
      },
      {
        id: 'sour_cream',
        title: { ru: 'Сметана', kz: 'Қаймақ' },
        category: 'dairy_eggs',
        queryTerms: ['сметана 20%', 'сметана 15%'],
        required: true,
      },
    ],
  },
  {
    id: 'sandwiches',
    title: { ru: 'Сэндвичи и тосты', kz: 'Сэндвичтер мен тосттар' },
    emoji: '🥪',
    aliases: ['сэндвич', 'бутерброд', 'тосты', 'бутерброды', 'sandwich'],
    roles: [
      {
        id: 'bread',
        title: { ru: 'Тостовый хлеб', kz: 'Тост наны' },
        category: 'bread',
        queryTerms: ['хлеб тостовый', 'хлеб для тостов harry', 'хлеб нарезка'],
        required: true,
      },
      {
        id: 'meat',
        title: { ru: 'Ветчина или филе индейки', kz: 'Ветчина немесе күркетауық' },
        category: 'deli',
        queryTerms: ['ветчина из индейки', 'ветчина нарезка', 'колбаса докторская нарезка'],
        required: true,
      },
      {
        id: 'cheese',
        title: { ru: 'Сыр ломтиками', kz: 'Тілімделген ірімшік' },
        category: 'dairy_eggs',
        queryTerms: ['сыр ломтики плавленый', 'сыр гауда ломтики', 'сыр hochland слайсы'],
        required: true,
      },
      {
        id: 'greens',
        title: { ru: 'Огурец и листья салата', kz: 'Қияр мен салат жапырақтары' },
        category: 'fruits_veg',
        queryTerms: ['огурцы свежие', 'салат листовой', 'помидоры'],
        required: false,
      },
    ],
  },
  {
    id: 'greek_salad',
    title: { ru: 'Греческий салат', kz: 'Грек салаты' },
    emoji: '🥗',
    aliases: ['греческий салат', 'греческий', 'салат греческий', 'greek salad'],
    roles: [
      {
        id: 'feta',
        title: { ru: 'Сыр Фета или Сиртаки', kz: 'Фета немесе Сиртаки ірімшігі' },
        category: 'dairy_eggs',
        queryTerms: ['сыр фета', 'сыр фетакса', 'сыр сиртаки рассольный'],
        required: true,
      },
      {
        id: 'veg',
        title: { ru: 'Огурцы, помидоры, болгарский перец', kz: 'Қияр, қызанақ, тәтті бұрыш' },
        category: 'fruits_veg',
        queryTerms: ['помидоры черри', 'огурцы короткоплодные', 'перец болгарский'],
        required: true,
      },
      {
        id: 'olives',
        title: { ru: 'Маслины без косточки', kz: 'Сүйексіз қара зәйтүн' },
        category: 'grocery',
        queryTerms: ['маслины без косточки', 'маслины иберика'],
        required: true,
      },
      {
        id: 'olive_oil',
        title: { ru: 'Оливковое масло Extra Virgin', kz: 'Зәйтүн майы Extra Virgin' },
        category: 'grocery',
        queryTerms: ['масло оливковое extra virgin', 'масло оливковое borges'],
        required: true,
      },
    ],
  },
  {
    id: 'okroshka',
    title: { ru: 'Окрошка освежающая', kz: 'Сергітетін окрошка' },
    emoji: '🥣',
    aliases: ['окрошка', 'окрошкаға', 'okroshka'],
    roles: [
      {
        id: 'sausage',
        title: { ru: 'Вареная колбаса', kz: 'Пісірілген шұжық' },
        category: 'deli',
        queryTerms: ['колбаса докторская', 'колбаса молочная'],
        required: true,
      },
      {
        id: 'kefir_kvas',
        title: { ru: 'Кефир или квас', kz: 'Айран немесе квас' },
        category: 'dairy_eggs',
        queryTerms: ['кефир 2.5%', 'айран', 'квас окрошечный'],
        required: true,
      },
      {
        id: 'veg_greens',
        title: { ru: 'Огурцы, редис, зеленый лук и укроп', kz: 'Қияр, шалғам, көк пияз бен аскөк' },
        category: 'fruits_veg',
        queryTerms: ['огурцы свежие', 'редис', 'лук зеленый', 'укроп'],
        required: true,
      },
      {
        id: 'eggs_potato',
        title: { ru: 'Яйца и картофель', kz: 'Жұмыртқа мен картоп' },
        category: 'dairy_eggs',
        queryTerms: ['яйцо куриное с1', 'картофель свежий'],
        required: true,
      },
    ],
  },
  {
    id: 'shorpa',
    title: { ru: 'Сорпа / Шорпа наваристая', kz: 'Дәмді шорпа' },
    emoji: '🍲',
    aliases: ['шорпа', 'сорпа', 'сурпа', 'сорпаға', 'shorpa'],
    roles: [
      {
        id: 'meat',
        title: { ru: 'Баранина или говядина на кости', kz: 'Сүйекті қой немесе сиыр еті' },
        category: 'meat',
        queryTerms: ['баранина на кости', 'говядина на кости', 'суповой набор'],
        required: true,
      },
      {
        id: 'potato_carrot',
        title: { ru: 'Картофель и морковь крупно', kz: 'Картоп және сәбіз' },
        category: 'fruits_veg',
        queryTerms: ['картофель крупный', 'морковь свежая', 'лук репчатый'],
        required: true,
      },
      {
        id: 'greens_spices',
        title: { ru: 'Зелень кинзы и черный перец', kz: 'Кинза жасыл шөбі және қара бұрыш' },
        category: 'fruits_veg',
        queryTerms: ['кинза свежая', 'перец черный молотый'],
        required: false,
      },
    ],
  },
  {
    id: 'pelmeni',
    title: { ru: 'Пельмени с соусом и зеленью', kz: 'Пельмен тұздықпен' },
    emoji: '🥟',
    aliases: ['пельмени', 'тұшпара', 'пельмендер', 'pelmeni'],
    roles: [
      {
        id: 'pelmeni_pack',
        title: { ru: 'Пельмени отборные', kz: 'Таңдаулы пельмендер' },
        category: 'frozen',
        queryTerms: ['пельмени сибирские', 'пельмени домашние', 'пельмени барон', 'пельмени'],
        required: true,
      },
      {
        id: 'butter',
        title: { ru: 'Сливочное масло', kz: 'Сары май' },
        category: 'dairy_eggs',
        queryTerms: ['масло сливочное 82.5%', 'масло сливочное 72.5%'],
        required: true,
      },
      {
        id: 'sour_cream',
        title: { ru: 'Сметана к пельменям', kz: 'Қаймақ' },
        category: 'dairy_eggs',
        queryTerms: ['сметана 15%', 'сметана 20%'],
        required: true,
      },
      {
        id: 'greens',
        title: { ru: 'Свежая зелень (укроп)', kz: 'Жаңа піскен аскөк' },
        category: 'fruits_veg',
        queryTerms: ['укроп свежий', 'лук зеленый'],
        required: false,
      },
    ],
  },
  {
    id: 'cutlets_puree',
    title: { ru: 'Котлеты с картофельным пюре', kz: 'Картоп езбесі қосылған котлет' },
    emoji: '🥔',
    aliases: ['пюре с котлетой', 'котлеты', 'пюре', 'картофельное пюре'],
    roles: [
      {
        id: 'meat_or_cutlets',
        title: { ru: 'Фарш домашний или котлеты', kz: 'Үй фаршы немесе котлет' },
        category: 'meat',
        queryTerms: ['фарш домашний говядина свинина', 'фарш говяжий', 'котлеты домашние'],
        required: true,
      },
      {
        id: 'potato',
        title: { ru: 'Картофель рассыпчатый', kz: 'Картоп' },
        category: 'fruits_veg',
        queryTerms: ['картофель свежий', 'картофель весовой'],
        required: true,
      },
      {
        id: 'milk_butter',
        title: { ru: 'Молоко и сливочное масло', kz: 'Сүт пен сары май' },
        category: 'dairy_eggs',
        queryTerms: ['масло сливочное 82.5%', 'молоко 3.2%'],
        required: true,
      },
      {
        id: 'onion',
        title: { ru: 'Лук репчатый', kz: 'Бас пияз' },
        category: 'fruits_veg',
        queryTerms: ['лук репчатый'],
        required: false,
      },
    ],
  },
]
