BEGIN;

SET LOCAL search_path = public, extensions, pg_temp;

-- ═══════════════════════════════════════════════════════════════
-- 034a — Search v3: brand aliases table + full keyword sync
-- ═══════════════════════════════════════════════════════════════

-- ═══════ 1. Brand aliases table ═══════

CREATE TABLE IF NOT EXISTS public.search_brand_aliases (
  id SERIAL PRIMARY KEY,
  alias TEXT NOT NULL,
  brand TEXT NOT NULL,
  category TEXT,
  subcategory TEXT,
  intent_boost NUMERIC DEFAULT 600,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (alias, brand)
);

GRANT SELECT ON public.search_brand_aliases TO anon, authenticated;

CREATE INDEX IF NOT EXISTS idx_search_brand_aliases_alias
  ON public.search_brand_aliases (alias);

INSERT INTO public.search_brand_aliases (alias, brand, category, subcategory, intent_boost) VALUES
  -- chocolate/candy
  ('сникерс','Snickers','sweets','chocolate',600),
  ('твикс','Twix','sweets','chocolate',600),
  ('баунти','Bounty','sweets','chocolate',600),
  ('кит-кат','KitKat','sweets','chocolate',600),
  ('киткат','KitKat','sweets','chocolate',600),
  ('милка','Milka','sweets','chocolate',600),
  ('нутелла','Nutella','sweets','chocolate',600),
  ('альпен голд','Alpen Gold','sweets','chocolate',600),
  ('альпенголд','Alpen Gold','sweets','chocolate',600),
  ('виспа','Wispa','sweets','chocolate',600),
  ('тофифи','Toffifee','sweets','candy',600),
  ('рошен','Roshen','sweets','candy',600),
  ('рахат','Рахат','sweets','candy',600),
  ('баян сулу','Баян Сулу','sweets','candy',600),
  ('победа','Победа','sweets','chocolate',600),
  ('россия','Россия','sweets','chocolate',600),
  ('риттер спорт','Ritter Sport','sweets','chocolate',600),
  ('линдт','Lindt','sweets','chocolate',600),
  ('плитка','Плитка','sweets','chocolate',600),
  -- beverages
  ('пепси','Pepsi','water_beverages','soda',600),
  ('фанта','Fanta','water_beverages','soda',600),
  ('спрайт','Sprite','water_beverages','soda',600),
  ('ред булл','Red Bull','water_beverages','energy',600),
  ('ред бул','Red Bull','water_beverages','energy',600),
  ('швепс','Schweppes','water_beverages','soda',600),
  ('добрый','Добрый','water_beverages','juice',600),
  ('ляззат','Ляззат','dairy_eggs','fermented',600),
  ('асем ай','Асем Ай','water_beverages','water',600),
  ('тассай','Tassay','water_beverages','water',600),
  ('нарзан','Нарзан','water_beverages','water',600),
  ('боржоми','Borjomi','water_beverages','water',600),
  ('бон аква','Bon Aqua','water_beverages','water',600),
  ('аквалайф','Aqualife','water_beverages','water',600),
  -- coffee/tea
  ('нескафе','Nescafe','tea_coffee','coffee',600),
  ('якобс','Jacobs','tea_coffee','coffee',600),
  ('тчибо','Tchibo','tea_coffee','coffee',600),
  ('лявазза','Lavazza','tea_coffee','coffee',600),
  ('ахмад','Ahmad','tea_coffee','tea',600),
  ('гринфилд','Greenfield','tea_coffee','tea',600),
  ('липтон','Lipton','tea_coffee','tea',600),
  ('дилма','Dilmah','tea_coffee','tea',600),
  ('маккофе','MacCoffee','tea_coffee','coffee',600),
  ('жокей','Жокей','tea_coffee','coffee',600),
  -- dairy
  ('эмил','Эмиль','dairy_eggs','milk',600),
  ('президент','President','dairy_eggs','cheese',600),
  ('савушкин','Савушкин','dairy_eggs','cheese',600),
  ('пармалат','Parmalat','dairy_eggs','milk',600),
  ('лактел','Lactel','dairy_eggs','milk',600),
  ('простоквашино','Простоквашино','dairy_eggs','milk',600),
  ('даниссимо','Danissimo','dairy_eggs','fermented',600),
  ('альпенланд','Alpenland','dairy_eggs','fermented',600),
  ('фрутоняня','ФрутоНяня','baby_food','puree',600),
  ('агуша','Агуша','baby_food','puree',600),
  ('деп','Dep','dairy_eggs','cream',600),
  ('адаль','Adal','dairy_eggs','milk',600),
  ('фудмастер','FoodMaster','dairy_eggs','fermented',600),
  ('foodmaster','FoodMaster','dairy_eggs','fermented',600),
  -- chips/snacks
  ('лейс','Lay''s','snacks','chips',600),
  ('лейз','Lay''s','snacks','chips',600),
  ('доритос','Doritos','snacks','chips',600),
  ('принглс','Pringles','snacks','chips',600),
  ('кдв','KDV','sweets','candy',600),
  ('гризли','Grizzly','snacks','chips',600),
  ('биг бон','Big Bon','snacks','chips',600),
  -- household
  ('фейри','Fairy','household','cleaning',600),
  ('доместос','Domestos','household','cleaning',600),
  ('мистер пропер','Mr. Proper','household','cleaning',600),
  ('биомио','Биомио','household','cleaning',600),
  ('тайд','Tide','household','laundry',600),
  -- baby
  ('нестожен','Nestogen','baby_food','formula',600),
  ('кабрита','Kabrita','baby_food','formula',600),
  ('нутрилон','Nutrilon','baby_food','formula',600),
  ('симилак','Similac','baby_food','formula',600),
  -- grocery
  ('увелка','Увелка','grocery','cereals',600),
  ('мистраль','Мистраль','grocery','rice',600),
  ('макфа','Makfa','grocery','pasta',600),
  ('барилла','Barilla','grocery','pasta',600),
  ('цесна','Цесна','grocery','flour',600),
  -- meat/deli
  ('мираторг','Мираторг','frozen','semi_finished',600),
  ('океан','Океан','fish','canned_fish',600),
  -- plant milk
  ('алпро','Alpro','dairy_eggs','milk',600),
  ('немолоко','Nemoloko','dairy_eggs','milk',600)
ON CONFLICT (alias, brand) DO NOTHING;

-- ═══════ 2. Full keyword sync ═══════

DELETE FROM public.search_category_keywords;

INSERT INTO public.search_category_keywords (keyword, category, subcategory, intent_boost) VALUES
  -- sweets/chocolate
  ('шоколадная паста','sweets','chocolate',400),
  ('шоколадное печенье','sweets','cookies',400),
  ('шоколадный батончик','sweets','chocolate',400),
  ('шоколадные конфеты','sweets','candy',400),
  ('шоколадная плитка','sweets','chocolate',400),
  ('молочный шоколад','sweets','chocolate',400),
  ('горький шоколад','sweets','chocolate',400),
  ('белый шоколад','sweets','chocolate',400),
  ('темный шоколад','sweets','chocolate',400),
  ('тёмный шоколад','sweets','chocolate',400),
  ('шоколад','sweets','chocolate',500),
  ('chocolate','sweets','chocolate',500),
  ('плитка','sweets','chocolate',400),
  ('виспа','sweets','chocolate',400),
  ('wispa','sweets','chocolate',400),
  ('счасть','sweets','chocolate',400),
  ('nutella','sweets','chocolate',400),
  -- sweets/cookies
  ('печенье','sweets','cookies',500),
  ('крекер','sweets','cookies',400),
  ('пряник','sweets','cookies',400),
  ('вафл','sweets','pastries',400),
  ('cookie','sweets','cookies',400),
  ('biscuit','sweets','cookies',400),
  ('бісквіт','sweets','cookies',400),
  ('бисквит','sweets','cookies',400),
  -- sweets/candy
  ('конфет','sweets','candy',400),
  ('карамел','sweets','candy',400),
  ('мармелад','sweets','candy',400),
  ('зефир','sweets','candy',400),
  ('драже','sweets','candy',400),
  ('маршмеллоу','sweets','candy',400),
  ('marshmallow','sweets','candy',400),
  ('леденец','sweets','candy',400),
  ('жевательн','sweets','candy',400),
  ('резинка жевательн','sweets','candy',400),
  ('орбит','sweets','candy',400),
  ('wrigley','sweets','candy',400),
  ('eclipse','sweets','candy',400),
  ('dirol','sweets','candy',400),
  ('m&m','sweets','candy',400),
  ('пудинг','sweets','candy',400),
  ('десерт','sweets','candy',400),
  ('пастила','sweets','candy',400),
  ('пастіла','sweets','candy',400),
  ('candy','sweets','candy',400),
  -- sweets/halva
  ('халв','sweets','halva',400),
  ('козинак','sweets','halva',400),
  ('рахат-лукум','sweets','halva',400),
  ('щербет','sweets','halva',400),
  ('чак-чак','sweets','halva',400),
  -- sweets/honey_jam
  ('мёд','sweets','honey_jam',400),
  ('варень','sweets','honey_jam',400),
  ('джем','sweets','honey_jam',400),
  ('honey','sweets','honey_jam',400),
  ('jam','sweets','honey_jam',400),
  ('сироп','sweets','honey_jam',400),
  ('топпинг','sweets','honey_jam',400),
  -- dairy_eggs/milk
  ('молок','dairy_eggs','milk',500),
  ('milk','dairy_eggs','milk',500),
  ('молочный напиток','dairy_eggs','milk',400),
  ('alpro','dairy_eggs','milk',400),
  ('nemoloko','dairy_eggs','milk',400),
  ('оших','dairy_eggs','milk',400),
  ('соев','dairy_eggs','milk',400),
  ('кокосов','dairy_eggs','milk',400),
  ('овсян','dairy_eggs','milk',400),
  ('миндальн','dairy_eggs','milk',400),
  -- dairy_eggs/fermented
  ('кефир','dairy_eggs','fermented',500),
  ('ряженк','dairy_eggs','fermented',400),
  ('йогурт','dairy_eggs','fermented',400),
  ('yogurt','dairy_eggs','fermented',400),
  ('снежок','dairy_eggs','fermented',400),
  ('кумыс','dairy_eggs','fermented',400),
  ('тан ','dairy_eggs','fermented',400),
  ('айран','dairy_eggs','fermented',400),
  ('курт','dairy_eggs','fermented',400),
  -- dairy_eggs/cheese
  ('сыр ','dairy_eggs','cheese',500),
  ('cheese','dairy_eggs','cheese',500),
  -- dairy_eggs/cottage
  ('сырок','dairy_eggs','cottage',400),
  ('творог','dairy_eggs','cottage',500),
  -- dairy_eggs/cream
  ('сметан','dairy_eggs','cream',400),
  ('сливк','dairy_eggs','cream',400),
  ('cream','dairy_eggs','cream',400),
  -- dairy_eggs/butter
  ('сливочное масло','dairy_eggs','butter',500),
  ('масло сливочное','dairy_eggs','butter',500),
  ('butter','dairy_eggs','butter',500),
  -- dairy_eggs/condensed_milk
  ('сгущенк','dairy_eggs','condensed_milk',400),
  ('сгущёнк','dairy_eggs','condensed_milk',400),
  -- dairy_eggs/eggs
  ('яйц','dairy_eggs','eggs',500),
  -- dairy_eggs/spread
  ('спред','dairy_eggs','spread',400),
  ('маргарин','dairy_eggs','spread',400),
  -- deli/sausage
  ('колбас','deli','sausage',500),
  ('сосиск','deli','sausage',400),
  ('сардельк','deli','sausage',400),
  ('шпикачк','deli','sausage',400),
  ('сервелат','deli','sausage',400),
  ('halal','deli','sausage',400),
  -- deli/pate
  ('паштет','deli','pate',400),
  -- deli/deli_meat
  ('ветчин','deli','deli_meat',400),
  ('балык','deli','deli_meat',400),
  ('нарезк','deli','deli_meat',400),
  ('рулет мясн','deli','deli_meat',400),
  -- deli/smoked
  ('салями','deli','smoked',400),
  ('копчён','deli','smoked',400),
  ('копчен','deli','smoked',400),
  ('курдюк','deli','smoked',400),
  -- deli/canned_meat
  ('тушёнк','deli','canned_meat',400),
  ('тушенк','deli','canned_meat',400),
  ('мясные консерв','deli','canned_meat',400),
  ('каша гречневая с говядин','deli','canned_meat',400),
  -- fish
  ('рыб','fish','fish',500),
  ('fish','fish','fish',400),
  ('креветк','fish','seafood',400),
  ('кальмар','fish','seafood',400),
  ('миди','fish','seafood',400),
  ('крабов','fish','seafood',400),
  ('палочки крабов','fish','seafood',400),
  ('крабовые палочки','fish','seafood',400),
  ('морепродукт','fish','seafood',400),
  ('икр','fish','seafood',400),
  ('нори','fish','seafood',400),
  ('сурими','fish','seafood',400),
  ('seafood','fish','seafood',400),
  ('тунец','fish','canned_fish',400),
  ('сайр','fish','canned_fish',400),
  ('сардин','fish','canned_fish',400),
  ('сельдь','fish','canned_fish',400),
  ('скумбри','fish','canned_fish',400),
  ('горбуш','fish','canned_fish',400),
  ('форел','fish','fish',400),
  -- meat
  ('говядин','meat','raw',400),
  ('свинин','meat','raw',400),
  ('баранин','meat','raw',400),
  ('фарш','meat','raw',400),
  ('meat','meat','raw',400),
  ('индейк','meat','poultry',400),
  ('куриц','meat','poultry',400),
  ('крыло','meat','poultry',400),
  -- water_beverages/juice
  ('сок','water_beverages','juice',500),
  ('нектар','water_beverages','juice',400),
  ('juice','water_beverages','juice',400),
  -- water_beverages/water
  ('вода','water_beverages','water',500),
  ('water','water_beverages','water',400),
  -- water_beverages/soda
  ('газировк','water_beverages','soda',400),
  ('coca-cola','water_beverages','soda',400),
  ('pepsi','water_beverages','soda',400),
  ('fanta','water_beverages','soda',400),
  ('sprite','water_beverages','soda',400),
  ('schweppes','water_beverages','soda',400),
  ('тоник','water_beverages','soda',400),
  ('soda','water_beverages','soda',400),
  -- water_beverages/lemonade
  ('лимонад','water_beverages','lemonade',400),
  ('квас','water_beverages','lemonade',400),
  ('комбуч','water_beverages','lemonade',400),
  ('кисель','water_beverages','lemonade',400),
  ('компот','water_beverages','lemonade',400),
  ('морс','water_beverages','lemonade',400),
  ('lipton','water_beverages','lemonade',400),
  ('напиток','water_beverages','lemonade',400),
  ('ice macchiato','water_beverages','lemonade',400),
  -- water_beverages/energy
  ('энергетик','water_beverages','energy',400),
  -- tea_coffee/tea
  ('чай','tea_coffee','tea',500),
  ('tea ','tea_coffee','tea',400),
  ('tea','tea_coffee','tea',400),
  -- tea_coffee/coffee
  ('кофе','tea_coffee','coffee',500),
  ('какао','tea_coffee','coffee',400),
  ('coffee','tea_coffee','coffee',400),
  ('jacobs','tea_coffee','coffee',400),
  ('macchiato','tea_coffee','coffee',400),
  -- snacks/chips
  ('чипс','snacks','chips',500),
  ('попкорн','snacks','chips',400),
  ('chips','snacks','chips',400),
  ('snack','snacks','chips',400),
  ('doritos','snacks','chips',400),
  -- snacks/crackers
  ('сухарик','snacks','crackers',400),
  ('сухар','snacks','crackers',400),
  ('гренк','snacks','crackers',400),
  ('тарталетк','snacks','crackers',400),
  ('бонжур','snacks','crackers',400),
  ('bien','snacks','crackers',400),
  -- snacks/nuts
  ('орех','snacks','nuts',400),
  ('миндал','snacks','nuts',400),
  ('фундук','snacks','nuts',400),
  ('арахис','snacks','nuts',400),
  ('фисташк','snacks','nuts',400),
  ('кешью','snacks','nuts',400),
  ('nuts','snacks','nuts',400),
  -- snacks/dried_fruits
  ('сухофрукт','snacks','dried_fruits',400),
  ('кураг','snacks','dried_fruits',400),
  ('изюм','snacks','dried_fruits',400),
  ('чернослив','snacks','dried_fruits',400),
  -- snacks/seeds
  ('семечк','snacks','seeds',400),
  ('подсолнечник','snacks','seeds',400),
  ('тыквенн','snacks','seeds',400),
  ('жареный','snacks','seeds',400),
  ('соленый','snacks','seeds',400),
  -- grocery/cereals
  ('круп','grocery','cereals',400),
  ('гречк','grocery','cereals',400),
  ('овсян','grocery','cereals',400),
  ('пшено','grocery','cereals',400),
  ('перлов','grocery','cereals',400),
  ('манн','grocery','cereals',400),
  ('чечевиц','grocery','cereals',400),
  -- grocery/pasta
  ('макарон','grocery','pasta',400),
  ('спагетти','grocery','pasta',400),
  ('паста','grocery','pasta',400),
  ('фунчоз','grocery','pasta',400),
  ('pasta','grocery','pasta',400),
  ('лапша','grocery','pasta',400),
  ('соба','grocery','pasta',400),
  ('tagliolini','grocery','pasta',400),
  -- grocery/rice
  ('рис','grocery','rice',500),
  ('rice','grocery','rice',400),
  -- grocery/flour
  ('мука','grocery','flour',500),
  ('flour','grocery','flour',400),
  ('кокосовая стружка','grocery','flour',400),
  ('крахмал','grocery','flour',400),
  ('желатин','grocery','flour',400),
  ('разрыхлитель','grocery','flour',400),
  ('ванил','grocery','flour',400),
  ('премикс','grocery','flour',400),
  -- grocery/sugar
  ('сахар','grocery','sugar',500),
  ('sugar','grocery','sugar',400),
  -- grocery/breakfast
  ('хлопь','grocery','breakfast',400),
  ('мюсл','grocery','breakfast',400),
  ('гранол','grocery','breakfast',400),
  ('завтрак','grocery','breakfast',400),
  ('отруб','grocery','breakfast',400),
  ('cereal','grocery','breakfast',400),
  ('muesli','grocery','breakfast',400),
  ('granola','grocery','breakfast',400),
  ('breakfast','grocery','breakfast',400),
  -- grocery/cooking_oil
  ('подсолнечное масло','grocery','cooking_oil',500),
  ('оливковое масло','grocery','cooking_oil',500),
  ('растительное масло','grocery','cooking_oil',500),
  ('масло подсолнеч','grocery','cooking_oil',500),
  ('масло оливков','grocery','cooking_oil',500),
  ('масло ','grocery','cooking_oil',400),
  ('oil','grocery','cooking_oil',400),
  -- grocery/salt
  ('соль','grocery','salt',400),
  ('лимонная кислота','grocery','salt',400),
  ('сода пищев','grocery','salt',400),
  -- grocery/vinegar
  ('уксус','grocery','vinegar',400),
  -- sauces_spices
  ('соус','sauces_spices','sauce',400),
  ('соевый соус','sauces_spices','soy_sauce',400),
  ('sauce','sauces_spices','sauce',400),
  ('майонез','sauces_spices','mayo_ketchup',400),
  ('кетчуп','sauces_spices','mayo_ketchup',400),
  ('специй','sauces_spices','spices',400),
  ('приправ','sauces_spices','condiments',400),
  ('перец','sauces_spices','spices',400),
  ('кунжут','sauces_spices','spices',400),
  ('spice','sauces_spices','spices',400),
  ('season','sauces_spices','condiments',400),
  ('condiment','sauces_spices','condiments',400),
  ('горчиц','sauces_spices','condiments',400),
  ('хрен','sauces_spices','condiments',400),
  ('бульон','sauces_spices','condiments',400),
  ('томатная паста','sauces_spices','condiments',400),
  -- bread
  ('хлеб','bread','bread',500),
  ('батон','bread','bread',400),
  ('лаваш','bread','lavash',400),
  ('лепёшк','bread','lavash',400),
  ('лепешк','bread','lavash',400),
  ('чиабатт','bread','pastry',400),
  ('булочк','bread','pastry',400),
  ('багет','bread','pastry',400),
  ('рулет','bread','pastry',400),
  ('ruellet','bread','pastry',400),
  ('bread','bread','bread',400),
  ('bakery','bread','pastry',400),
  ('хлебц','bread','crispbread',400),
  ('слайс','bread','crispbread',400),
  -- frozen/ice_cream
  ('морожен','frozen','ice_cream',500),
  ('эскимо','frozen','ice_cream',400),
  ('пломбир','frozen','ice_cream',400),
  -- frozen/semi_finished
  ('пельмен','frozen','semi_finished',500),
  ('вареник','frozen','semi_finished',400),
  ('котлет','frozen','semi_finished',400),
  ('тефтел','frozen','semi_finished',400),
  ('фрикадельк','frozen','semi_finished',400),
  ('наггетс','frozen','semi_finished',400),
  ('полуфабрикат','frozen','semi_finished',400),
  ('блинчик','frozen','semi_finished',400),
  ('пицц','frozen','semi_finished',400),
  ('тесто','frozen','semi_finished',400),
  ('жаренк','frozen','semi_finished',400),
  ('сырник','frozen','semi_finished',400),
  ('замороженн','frozen','frozen_veg',400),
  ('frozen','frozen','semi_finished',400),
  -- fruits_veg
  ('овощ','fruits_veg','vegetables',400),
  ('картофел','fruits_veg','vegetables',400),
  ('помидор','fruits_veg','vegetables',400),
  ('томат','fruits_veg','vegetables',400),
  ('окра','fruits_veg','vegetables',400),
  ('спарж','fruits_veg','vegetables',400),
  ('зелень','fruits_veg','greens',400),
  ('фрукт','fruits_veg','fruits',400),
  ('яблок','fruits_veg','fruits',400),
  ('банан','fruits_veg','fruits',400),
  ('груда','fruits_veg','fruits',400),
  ('груш','fruits_veg','fruits',400),
  ('огурц','fruits_veg','pickles',400),
  ('солень','fruits_veg','pickles',400),
  ('маринован','fruits_veg','pickles',400),
  ('оливк','fruits_veg','olives',400),
  ('маслин','fruits_veg','olives',400),
  ('шампиньон','fruits_veg','canned_veg',400),
  ('гриб','fruits_veg','canned_veg',400),
  ('кукуруз','fruits_veg','canned_veg',400),
  ('горошек','fruits_veg','canned_veg',400),
  ('фасол','fruits_veg','canned_veg',400),
  ('нут ','fruits_veg','canned_veg',400),
  ('бондинг','fruits_veg','canned_veg',400),
  ('canned','fruits_veg','canned_veg',400),
  -- baby_food
  ('фрутоняня','baby_food','puree',400),
  ('агуша','baby_food','puree',400),
  ('детское питан','baby_food','puree',400),
  ('пюре','baby_food','puree',400),
  ('детская каш','baby_food','cereal',400),
  ('смесь молочн','baby_food','formula',400),
  ('kabrita','baby_food','formula',400),
  ('nestle шагайка','baby_food','cereal',400),
  ('смесь nestle','baby_food','formula',400),
  ('nestogen','baby_food','formula',400),
  -- ready_meals
  ('суп ','ready_meals','soups',400),
  ('быстрого приготовлен','ready_meals','instant',400),
  ('лапша быстр','ready_meals','instant',400),
  ('доширак','ready_meals','instant',400),
  ('роллтон','ready_meals','instant',400),
  -- healthy (attributes — lower boost)
  ('протеин','healthy','protein',300),
  ('белковый батончик','healthy','protein',300),
  ('без сахара','healthy','sugar_free',300),
  ('б.сах','healthy','sugar_free',300),
  ('безглютен','healthy','gluten_free',300),
  ('без глютен','healthy','gluten_free',300),
  ('глютен-free','healthy','gluten_free',300),
  ('пп-','healthy','diet',300),
  ('сахарозамен','healthy','sugar_free',300),
  ('стеви','healthy','sugar_free',300),
  ('эритрит','healthy','sugar_free',300),
  ('дәрумен','healthy','vitamins',300),
  ('витамин','healthy','vitamins',300),
  ('бад','healthy','supplements',300),
  ('омега','healthy','supplements',300),
  -- personal_care
  ('шампун','personal_care','shampoo',400),
  ('мыло','personal_care','soap',400),
  ('крем ','personal_care','cream',400),
  ('зубн','personal_care','dental',400),
  ('гель для душа','personal_care','hygiene',400),
  ('дезодорант','personal_care','hygiene',400),
  ('гель-уход','personal_care','hygiene',400),
  ('скраб','personal_care','cream',400),
  ('скраб для лиц','personal_care','cream',400),
  ('тоник для лиц','personal_care','cream',400),
  ('garnier','personal_care','cream',400),
  ('nivea','personal_care','hygiene',400),
  -- household
  ('корм','household','pet_food',400),
  ('лакомство для','household','pet_food',400),
  ('моющ','household','cleaning',400),
  ('салфетк','household','paper',400),
  ('бумажн','household','paper',400),
  ('стиральн','household','laundry',400),
  ('порошок','household','laundry',400),
  ('подгузник','household','hygiene',400),
  ('трусики','household','hygiene',400),
  ('гель для посуд','household','cleaning',400),
  ('fairy','household','cleaning',400),
  ('domestos','household','cleaning',400),
  ('mr.proper','household','cleaning',400),
  ('средство','household','cleaning',400),
  ('спрей','household','cleaning',400),
  ('биомио','household','cleaning',400),
  ('oknomoyka','household','cleaning',400),
  ('master fresh','household','cleaning',400),
  ('зеленая','household','cleaning',400),
  -- additional grocery
  ('солнечная кухня','sweets','candy',400),
  ('сибирский кедр','sweets','candy',400),
  (' набор','sweets','candy',400),
  ('сет праздничн','sweets','candy',400)
ON CONFLICT (keyword) DO NOTHING;

COMMIT;
