-- Fix: repopulate search_category_keywords (was deleted by 034a but INSERT failed)
INSERT INTO public.search_category_keywords (keyword, category, subcategory, intent_boost) VALUES
('шоколадная паста','sweets','chocolate',400),('шоколадное печенье','sweets','cookies',400),('шоколадный батончик','sweets','chocolate',400),('шоколадные конфеты','sweets','candy',400),('шоколадная плитка','sweets','chocolate',400),('молочный шоколад','sweets','chocolate',400),('горький шоколад','sweets','chocolate',400),('белый шоколад','sweets','chocolate',400),('темный шоколад','sweets','chocolate',400),('тёмный шоколад','sweets','chocolate',400);
INSERT INTO public.search_category_keywords (keyword, category, subcategory, intent_boost) VALUES
('шоколад','sweets','chocolate',500),('chocolate','sweets','chocolate',500),('плитка','sweets','chocolate',400),('виспа','sweets','chocolate',400),('wispa','sweets','chocolate',400),('счасть','sweets','chocolate',400),('nutella','sweets','chocolate',400),('печенье','sweets','cookies',500),('крекер','sweets','cookies',400),('пряник','sweets','cookies',400);
INSERT INTO public.search_category_keywords (keyword, category, subcategory, intent_boost) VALUES
('вафл','sweets','pastries',400),('cookie','sweets','cookies',400),('biscuit','sweets','cookies',400),('бісквіт','sweets','cookies',400),('бисквит','sweets','cookies',400),('конфет','sweets','candy',400),('карамел','sweets','candy',400),('мармелад','sweets','candy',400),('зефир','sweets','candy',400),('драже','sweets','candy',400);
INSERT INTO public.search_category_keywords (keyword, category, subcategory, intent_boost) VALUES
('маршмеллоу','sweets','candy',400),('marshmallow','sweets','candy',400),('леденец','sweets','candy',400),('жевательн','sweets','candy',400),('резинка жевательн','sweets','candy',400),('орбит','sweets','candy',400),('wrigley','sweets','candy',400),('eclipse','sweets','candy',400),('dirol','sweets','candy',400),('m&m','sweets','candy',400);
INSERT INTO public.search_category_keywords (keyword, category, subcategory, intent_boost) VALUES
('пудинг','sweets','candy',400),('десерт','sweets','candy',400),('пастила','sweets','candy',400),('пастіла','sweets','candy',400),('candy','sweets','candy',400),('халв','sweets','halva',400),('козинак','sweets','halva',400),('рахат-лукум','sweets','halva',400),('щербет','sweets','halva',400),('чак-чак','sweets','halva',400);
INSERT INTO public.search_category_keywords (keyword, category, subcategory, intent_boost) VALUES
('мёд','sweets','honey_jam',400),('варень','sweets','honey_jam',400),('джем','sweets','honey_jam',400),('honey','sweets','honey_jam',400),('jam','sweets','honey_jam',400),('сироп','sweets','honey_jam',400),('топпинг','sweets','honey_jam',400),('молок','dairy_eggs','milk',500),('milk','dairy_eggs','milk',500),('молочный напиток','dairy_eggs','milk',400);
INSERT INTO public.search_category_keywords (keyword, category, subcategory, intent_boost) VALUES
('alpro','dairy_eggs','milk',400),('nemoloko','dairy_eggs','milk',400),('оших','dairy_eggs','milk',400),('соев','dairy_eggs','milk',400),('кокосов','dairy_eggs','milk',400),('овсян','dairy_eggs','milk',400),('миндальн','dairy_eggs','milk',400),('кефир','dairy_eggs','fermented',500),('ряженк','dairy_eggs','fermented',400),('йогурт','dairy_eggs','fermented',400);
INSERT INTO public.search_category_keywords (keyword, category, subcategory, intent_boost) VALUES
('yogurt','dairy_eggs','fermented',400),('снежок','dairy_eggs','fermented',400),('кумыс','dairy_eggs','fermented',400),('тан ','dairy_eggs','fermented',400),('айран','dairy_eggs','fermented',400),('курт','dairy_eggs','fermented',400),('сыр ','dairy_eggs','cheese',500),('cheese','dairy_eggs','cheese',500),('сырок','dairy_eggs','cottage',400),('творог','dairy_eggs','cottage',500);
INSERT INTO public.search_category_keywords (keyword, category, subcategory, intent_boost) VALUES
('сметан','dairy_eggs','cream',400),('сливк','dairy_eggs','cream',400),('cream','dairy_eggs','cream',400),('сливочное масло','dairy_eggs','butter',500),('масло сливочное','dairy_eggs','butter',500),('butter','dairy_eggs','butter',500),('сгущенк','dairy_eggs','condensed_milk',400),('сгущёнк','dairy_eggs','condensed_milk',400),('яйц','dairy_eggs','eggs',500),('спред','dairy_eggs','spread',400);
INSERT INTO public.search_category_keywords (keyword, category, subcategory, intent_boost) VALUES
('маргарин','dairy_eggs','spread',400),('колбас','deli','sausage',500),('сосиск','deli','sausage',400),('сардельк','deli','sausage',400),('шпикачк','deli','sausage',400),('сервелат','deli','sausage',400),('halal','deli','sausage',400),('паштет','deli','pate',400),('ветчин','deli','deli_meat',400),('балык','deli','deli_meat',400);
INSERT INTO public.search_category_keywords (keyword, category, subcategory, intent_boost) VALUES
('нарезк','deli','deli_meat',400),('рулет мясн','deli','deli_meat',400),('салями','deli','smoked',400),('копчён','deli','smoked',400),('копчен','deli','smoked',400),('курдюк','deli','smoked',400),('тушёнк','deli','canned_meat',400),('тушенк','deli','canned_meat',400),('мясные консерв','deli','canned_meat',400),('каша гречневая с говядин','deli','canned_meat',400);
INSERT INTO public.search_category_keywords (keyword, category, subcategory, intent_boost) VALUES
('рыб','fish','fish',500),('fish','fish','fish',400),('креветк','fish','seafood',400),('кальмар','fish','seafood',400),('миди','fish','seafood',400),('крабов','fish','seafood',400),('палочки крабов','fish','seafood',400),('крабовые палочки','fish','seafood',400),('морепродукт','fish','seafood',400),('икр','fish','seafood',400);
INSERT INTO public.search_category_keywords (keyword, category, subcategory, intent_boost) VALUES
('нори','fish','seafood',400),('сурими','fish','seafood',400),('seafood','fish','seafood',400),('тунец','fish','canned_fish',400),('сайр','fish','canned_fish',400),('сардин','fish','canned_fish',400),('сельдь','fish','canned_fish',400),('скумбри','fish','canned_fish',400),('горбуш','fish','canned_fish',400),('форел','fish','fish',400);
INSERT INTO public.search_category_keywords (keyword, category, subcategory, intent_boost) VALUES
('говядин','meat','raw',400),('свинин','meat','raw',400),('баранин','meat','raw',400),('фарш','meat','raw',400),('meat','meat','raw',400),('индейк','meat','poultry',400),('куриц','meat','poultry',400),('крыло','meat','poultry',400),('сок','water_beverages','juice',500),('нектар','water_beverages','juice',400);
INSERT INTO public.search_category_keywords (keyword, category, subcategory, intent_boost) VALUES
('juice','water_beverages','juice',400),('вода','water_beverages','water',500),('water','water_beverages','water',400),('газировк','water_beverages','soda',400),('coca-cola','water_beverages','soda',400),('pepsi','water_beverages','soda',400),('fanta','water_beverages','soda',400),('sprite','water_beverages','soda',400),('schweppes','water_beverages','soda',400),('тоник','water_beverages','soda',400);
ON CONFLICT (keyword) DO NOTHING;
